# Generated by Django 4.2.1 on 2023-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_total', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='payment_images/')),
                ('customer', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
