# Generated by Django 4.2.1 on 2023-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('number_of_stars', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
