# Generated by Django 4.2.1 on 2023-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('product', models.CharField(max_length=255)),
                ('shipment_cost', models.IntegerField()),
                ('payment_options', models.CharField(max_length=255)),
            ],
        ),
    ]
