# Generated by Django 4.2.1 on 2023-06-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('shipment_cost', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
